### ISSUE TITLE
Hi! Can you add support of api.distribution.mediadotech.com ?

### ISSUE THREAD

**Issue by EdShedisson** [MrCocoNuat/clip-studio-reader-downloader#1]

**Comment by MrCocoNuat** [comment]
Hello,

I will need at least a link to where a book is distributed on this reader to check. Is it a paid site?

**Comment by EdShedisson** [comment]
> Hello,
> 
> I will need at least a link to where a book is distributed on this reader to check. Is it a paid site?

Yup. It's Pixiv Comic. I can give u a link and creditentials in private message.

**Comment by MrCocoNuat** [comment]
Ok, I can be reached on discord at `@coconuat`. I cannot promise to get this done soon, though, especially if the reader has some complex features or obfuscation.

**Comment by MrCocoNuat** [comment]
fixed in https://github.com/MrCocoNuat/clip-studio-reader-downloader/commit/21e2129d267e69b88f6b335f462788386c91df23
