### ISSUE TITLE
Hi! Can you add support of https://comic.iowl.jp/

### ISSUE THREAD

**Issue by kcMiG** [MrCocoNuat/clip-studio-reader-downloader#2]
These links are to guide you:
https://comic.iowl.jp/titles/182198/volumes
https://comic.iowl.jp/titles/147403/volumes

**Comment by MrCocoNuat** [comment]
Hi,
Can you try the newest changes out? You can update your userscript via your userscript manager or at the [GreasyFork page](https://greasyfork.org/en/scripts/481576-clip-studio-reader-downloader). If everything is good, please consider dropping a star on the repository!

**Comment by kcMiG** [comment]
The script works fine on Pixiv but sometimes fails on the other 2 sites. I solved that problem by adding a 3 second delay to the script so that the page loads and then the script runs.

**Comment by MrCocoNuat** [comment]
Interesting, do you mean in addition to the timer at first page load? 

Anyways, it is time to remove that page load timer, it was a quick fix ok for my use, but if other people with various browser/hardware configurations are using it... better to use an actual event listener

**Comment by kcMiG** [comment]
Yes, I added:
 window.addEventListener('load', () => {
 setTimeout(async () => {
 
 _**script**_
 
 }, 3000);
 });

**Comment by MrCocoNuat** [comment]
Ok, a proper check that the reader has actually loaded (instead of a static timer) should do it. Can you confirm?

**Comment by kcMiG** [comment]
Yes, it works perfect. Thank you.
