### ISSUE TITLE
Unscramble code

### ISSUE THREAD

**Issue by rainrdx** [MrCocoNuat/clip-studio-reader-downloader#7]
Thank you for maintaining this codebase. I want to provide a reference on the unscamble code for clip studio reader. Instead of working on individual implementations of the clip studio reader, maybe you want to consider this code? My test of it shows that it is generally applicable to the clip studio reader variants that I have access to.

https://github.com/heixxxxxx/ebook_comic_download/blob/main/comicJs/hontoBook.js

**Comment by MrCocoNuat** [comment]
Hi, thank you for using it!

That repository appears to be working from a lower level, requesting canvas data directly and then unscrambling it according to the specific algorithm used per site. This way, each site still needs individual support for the unscrambling algorithm though.

This userscript works on the document level after everything has been unscrambled already, so there is no need for that anymore. Individual support for user interfaces is still required, but I am working on a change to support readers in a much more general way. When that is done, it will greatly reduce the support workload.

Also, their repository does not publish a license, so it is by default under copyright with all rights reserved (apart from those given by the ToS of Github). I cannot pull anything from it.

If you have any more suggestions pertaining to this feel free to reopen.
