### ISSUE TITLE
SIngle page downloading not properly working

### ISSUE THREAD

**Issue by NotGura** [MrCocoNuat/clip-studio-reader-downloader#8]
Site where I encountered the issue: api.distribution.mediadotech.com / Pixiv Comics
Browser: Firefox 130.0 (64-bit)
Extension: Tampermonkey 5.1.1

Issue: When resizing the browser as to only show a single page instead of double pages, the script proceeds to download only the first half of the whole book. 

I assume it must be something related to the page count for the whole book that's half of amount when viewing in single page mode.

**Comment by MrCocoNuat** [comment]
Hi,

This seems pretty likely, I only remember testing with the standard 2-page layout. Do you have a link to the specific reader page or bookstore page? It seems that pixiv comics has started using multiple readers, only some of which this script currently supports.

Thank you for using the script, and for the detailed issue report!

**Comment by NotGura** [comment]
I dunno if it's going to help given that it's a link for a book I bought but here it is.
https://api.distribution.mediadotech.com/viewers/bsreader/v2/index.html?c=BT000148914100200201900209_001&cgi=https://api.distribution.mediadotech.com/distributions/contents/bsreader/dizeapam&colophon=&colophon_size=&colophon_type=&favicon_path=&finish_reading=&logo=&margin=0&p=%7B%22b%22%3A%22%22%2C%22c%22%3A%22%22%2C%22f%22%3A%22%22%2C%22l%22%3A%22%22%2C%22m%22%3A%22%22%2C%22r%22%3A%22close%22%2C%22z%22%3A%22%22%7D&param=eyJqZGNuIjoiIiwiZGlzdHJpYnV0aW9uSWQiOiI4N2MzMzJkMi04MGY5LTQ3YzAtYmY3NC0wOTI3N2IzOThmNTkiLCJjb250ZW50RmlsZUlkIjoiQlQwMDAxNDg5MTQxMDAyMDAyMDE5MDAyMDlfMDAxIiwiY29udGVudEZpbGVWZXJzaW9uIjoyMDI0MDYxNzE2MDAzNywidmlld2VySUQiOiJic3JlYWRlciIsInN0b3JlSWQiOiJwaXhpdmNfaSIsInVzZXJJZCI6IjIyMjYxMjkxIiwiZXhwaXJlZEF0IjoxNzI2MzQ4OTc2LCJzdGFydExpbWl0QXQiOjE3MjYyNjQzNzYsImNwaWQiOiIzZTRjNTlmODJjYTNiN2RhZDkzZTRlMzUzNDg5NjU5YiIsImlzVXNlTmV4dFNlYXJjaCI6ZmFsc2UsImNvZGUiOiIiLCJpc0Zyb21DaGVja0NvbnRlbnRzQVBJIjpmYWxzZSwiY29udGVudEZvcm0iOjEsImNvbnRlbnROYW1lIjoiIiwiY2F0ZWdvcnlJZCI6MSwibGFzdFVybCI6IiIsInNoYXJlVVJMIjoiIiwiY29sb3Bob24iOiIiLCJjb2xvcGhvblR5cGUiOjIsImNvbG9waG9uU2l6ZSI6IiIsImlzQ2hlY2tDb29raWUiOnRydWUsInRhZ01hbmFnZXJJZCI6IiIsImxhc3RQYWdlRnJhbWVTaXplIjpudWxsLCJzdG9yZVVSTCI6IiIsInN0b3JlTmFtZSI6IiIsInN0b3JlTG9nb1VSTCI6IiIsIkJpbkJNZW51TW9kZSI6MCwicHVibGlzaGVySUQiOiI5MDU4IiwiaXNMaWJyYXJ5Vm9pY2VFbmFibGUiOmZhbHNlfQ%3D%3D.faaf8cadec713a9210f815c15c982d8169c3ef3d7b7b9907966077bcb0b26725a7d400578ae5bc13c89177516d57dc3af008f491599ffcf2c040399e01516104&popup=&popup_size=&splash=&splash_color=&splash_delay=&splash_size=&t=dummy&title=&tutorial=&url=close

**Comment by MrCocoNuat** [comment]
If it is a paid book then yes, a direct reader link won't work. Do you have the store page? That way I can buy it if I don't find another suitable book.

**Comment by NotGura** [comment]
Here https://comic.pixiv.net/works/9387

**Comment by MrCocoNuat** [comment]
Ok, thanks. I am able to replicate this issue. Working on it!

**Comment by MrCocoNuat** [comment]
This should be fixed with 953a2bd - version 1.8 of the userscript, I tested this only indirectly, as I already have a collection of books on Honto that exhibit this bug and I believe that Pixiv should be fixed in the same way. 

Can you try the newest changes out? You can update your userscript via your userscript manager or at the [GreasyFork page](https://greasyfork.org/en/scripts/481576-clip-studio-reader-downloader). If everything is good, please consider dropping a star on the repository!

**Comment by MrCocoNuat** [comment]
~~GreasyFork is throwing a fit at the inclusion of certain libraries... until I resolve that, for now please update by manually editing the script to the latest version in this repository.~~
Ok, that is fixed

**Comment by NotGura** [comment]
Thanks a lot for your work!
