### ISSUE TITLE
Can you add Nadeshiko Shoten

### ISSUE THREAD

**Issue by shionsaionji** [MrCocoNuat/clip-studio-reader-downloader#9]
https://nadeshiko-shoten.jp/
https://bs.comicdc.jp/e02701mh5/v2/clipstudioreader_hybrid/index.php

**Comment by MrCocoNuat** [comment]
Hi,
Can you try the newest changes out (script version 1.9)? You can update your userscript via your userscript manager or at the [GreasyFork page](https://greasyfork.org/en/scripts/481576-clip-studio-reader-downloader). If everything is good, please consider dropping a star on the repository!

**Comment by MrCocoNuat** [comment]
It's been a week, so I'll assume version 1.9 is working for you. Thanks for using this script!
